import { useEffect, useMemo, useState } from 'react'
import { SettingsContext } from './SettingsContext.js'
import { formatMessage } from '../utils/i18n.js'

const STORAGE_KEY = 'wanchun-settings:v1'
const DEFAULT_SETTINGS = { language: 'zh-TW', reduceMotion: false, highContrast: false }

const MESSAGES = {
  'zh-TW': {
    'nav.taiwan': '台灣', 'nav.stamps': '集章', 'nav.collection': '圖鑑', 'nav.journal': '手札', 'nav.points': '點數', 'nav.itinerary': '行程',
    'nav.collapse': '收合底部導覽', 'nav.expand': '展開底部導覽', 'nav.main': '主要導覽',
    'drawer.open': '開啟選單', 'drawer.close': '關閉選單', 'drawer.navigation': '導覽選單', 'drawer.other': '其他頁面',
    'drawer.stampbook': '集章簿', 'drawer.photos': '照片圖鑑', 'drawer.news': '活動', 'drawer.settings': '設定', 'drawer.friends': '好友', 'drawer.profile': '個人資料', 'drawer.credits': '資料與授權',
    'session.current': '目前玩家', 'session.disconnected': '尚未連接 LINE', 'session.progress': '萬春宮任務 {completed}／{total}', 'session.loginHint': '進入任務時會請你登入', 'session.mock': '已登入', 'session.connect': '連接 LINE',
    'common.backMap': '返回地圖', 'common.retry': '重試', 'common.close': '關閉', 'common.loading': '載入中…', 'common.error': '發生錯誤', 'common.noData': '尚無資料',
    'collection.eyebrow': '文化記憶', 'collection.title': '照片圖鑑', 'collection.collected': '已收藏 {count}/{total} 區', 'collection.intro': '完成整個鄉鎮市區的宮廟探索後，該地的文化記憶照片會收進圖鑑。',
    'collection.unlockCentral': '完成中區所有宮廟後解鎖', 'collection.explore': '前往探索', 'collection.aria': '依行政區分類的文化記憶收藏', 'collection.empty': '尚未收藏', 'collection.loading': '行政區資料載入中…', 'collection.loadFailed': '行政區資料載入失敗', 'collection.regionCount': '{count} 個行政區', 'collection.districtCount': '{count} 區',
    'collection.centralLocation': '台中市・中區', 'collection.centralTitle': '昔日中區街市', 'collection.centralDescription': '街市人潮熙攘，見證中區商業繁華。', 'collection.centralImageAlt': '從高處俯瞰昔日台中市中區街市，人群與攤販聚集於街道兩側', 'collection.centralSource': '使用者提供之歷史照片；原始典藏來源與授權資訊待補。',
    'stampbook.loading': '正在整理宮廟印章…', 'stampbook.loadFailed': '集章簿資料載入失敗', 'stampbook.reload': '重新載入', 'stampbook.eyebrow': '宮廟文化收藏', 'stampbook.title': '集章簿', 'stampbook.collectedCount': '已收藏 {count}/{total} 間',
    'stampbook.emptyTitle': '你的集章簿還是空的', 'stampbook.emptyBody': '完成第一間宮廟探索後，專屬印章就會出現在這裡。', 'stampbook.goMap': '前往地圖', 'stampbook.aria': '依縣市與行政區分類的宮廟印章', 'stampbook.noMatches': '沒有符合條件的印章', 'stampbook.adjust': '調整收藏狀態後再看看。',
    'stampbook.completedDistricts': '已完成 {completed} / {total} 區', 'stampbook.templeCount': '{count} 間宮廟', 'stampbook.none': '尚未收藏', 'stampbook.collected': '已收藏', 'stampbook.notCollected': '尚未取得', 'stampbook.cardLabel': '{temple}，{location}，{state}',
    'stampbook.closeDetail': '關閉印章詳情', 'stampbook.exclusive': '宮廟專屬印章', 'stampbook.stampAlt': '{temple}專屬印章', 'stampbook.unknown': '尚未取得的印章', 'stampbook.acquiredDate': '取得日期：{date}', 'stampbook.acquiredDescription': '完成「{temple}探索」後取得。', 'stampbook.lockedDescription': '完成該宮廟的探索後，即可收藏這枚專屬印章。', 'stampbook.viewTemple': '查看宮廟', 'stampbook.viewJournal': '查看旅程紀錄',
    'collectible.close': '關閉收藏介紹', 'collectible.date': '取得日期・{date}',
    'news.eyebrow': '文化活動情報', 'news.title': '活動', 'news.intro': '沿著節慶與香路出發，收藏期間限定的文化記憶。', 'news.tags': '活動標籤', 'news.limited': '#期間限定', 'news.taichung': '#台中市', 'news.mazu': '#媽祖', 'news.eventTitle': '大甲媽祖遶境', 'news.time': '時間', 'news.region': '地區', 'news.regions': '台中・彰化・雲林・嘉義',
    'news.memory': '活動圖鑑', 'news.unlocked': '已解鎖', 'news.locked': '尚未解鎖', 'news.memoryLocked': '活動圖鑑尚未解鎖', 'news.memoryZoom': '放大大甲媽祖遶境歷史照片', 'news.imageAlt': '大甲媽祖遶境歷史照片', 'news.stamps': '期間限定印章', 'news.stampsHelp': '完成沿途任務後依序解鎖', 'news.stampRow': '{count} 枚{state}的期間限定印章', 'news.stampZoom': '放大{stamp}印章', 'news.stampAlt': '{stamp}印章', 'news.eventLocation': '大甲媽祖遶境・期間限定', 'news.stampTitle': '{stamp}紀念印章', 'news.stampDescription': '完成遶境路線第 {number} 段後取得。', 'news.memoryTitle': '大甲媽祖遶境文化記憶', 'news.memoryDescription': '完成期間限定遶境任務後收藏的歷史記憶。',
    'news.stamp.0': '起駕', 'news.stamp.1': '彰化', 'news.stamp.2': '西螺', 'news.stamp.3': '新港', 'news.stamp.4': '祝壽', 'news.stamp.5': '回程', 'news.stamp.6': '安座',
    'reward.remaining': '確認後還有 {count} 項獎勵', 'reward.confirm': '確認',
    'demo.eyebrow': '展示工具', 'demo.title': 'Demo 特殊面板', 'demo.close': '關閉', 'demo.intro': '開關會保留在此裝置，登出或切換 LINE 帳號後仍會套用。', 'demo.loginReset': '登入後才能重製當前帳號。', 'demo.resetDone': '當前帳號已重製',
    'demo.central.title': '中區完成', 'demo.central.description': '完成中區全部宮廟、點亮錨點，並取得所有印章與中區圖鑑。', 'demo.map.title': '全台填色', 'demo.map.description': '套用固定的縣市完成與鄉鎮市區探索中配色。', 'demo.event.title': '期間限定', 'demo.event.description': '完成大甲媽祖遶境七枚印章並解鎖活動圖鑑。', 'demo.rewards.title': '彈跳通知', 'demo.rewards.description': '依序展示印章、圖鑑、LINE POINTS 與永久貼圖。', 'demo.reset.title': '重製當前帳號進度', 'demo.reset.description': '清除任務、集章、圖鑑、行程與個人頭像等本機設定。',
    'experience.temple': '萬春宮', 'experience.location': '台中市中區', 'experience.back': '返回萬春宮', 'experience.title': '{temple}探索任務', 'experience.reset': '重新開始', 'experience.resetTitle': '重新開始流程', 'experience.progress': '探索進度', 'experience.touch': 'LINE Touch', 'experience.photo': '拍照探索', 'experience.game': '互動遊戲', 'experience.disclaimer': 'LINE Touch 採感應體驗；拍照可使用裝置相機在本機對位，或從相簿選取。影像不會自動上傳。',
    'touch.kicker': 'LINE Touch・文化探索', 'touch.success': '感應成功', 'touch.detecting': '正在感應…', 'touch.title': '開啟宮廟探索', 'touch.opened': '{temple}探索已開啟', 'touch.keepNear': '請讓手機保持靠近感應區', 'touch.help': '將手機靠近感應區，開始今天的文化任務。', 'touch.simulate': '模擬感應', 'touch.reading': '正在讀取宮廟探索資訊', 'touch.stamping': '即將為你蓋上探索印章',
    'stampScene.defaultContinue': '開始拍照探索', 'stampScene.certificate': '探索憑證', 'stampScene.acquiring': '正在取得印章', 'stampScene.opened': '{temple}探索已開啟', 'stampScene.title': '宮廟印章蓋印中', 'stampScene.saved': '專屬印章已留在探索卡上。', 'stampScene.wait': '感應成功，請稍候片刻。', 'stampScene.journey': '文化行旅', 'stampScene.slot': '探索章位', 'stampScene.alt': '{temple}朱紅印章', 'stampScene.impact': '啪！', 'stampScene.complete': '{temple}數位蓋章已完成',
    'transition.photoTitle': '準備拍照探索', 'transition.gameTitle': '遊戲載入中…', 'transition.photoBody': '留下你在{temple}的探索紀錄', 'transition.gameBody': '準備進入{temple}小挑戰',
    'photoDemo.kicker': '拍照探索・實景對位', 'photoDemo.completeTitle': '拍照探索完成', 'photoDemo.unlockedTitle': '完整照片已解鎖', 'photoDemo.title': '補上照片缺口', 'photoDemo.nextGame': '接下來，完成{temple}的小遊戲吧！', 'photoDemo.help': '將現場鏡頭對準原始照片的缺口，完成後才會解鎖照片。', 'photoDemo.stageLabel': '{temple}原始照片，中央缺口顯示相機即時畫面', 'photoDemo.camera': '相機畫面', 'photoDemo.checking': '正在確認位置…', 'photoDemo.resultAlt': '{temple}實景對位完成照片', 'photoDemo.album': '相簿照片', 'photoDemo.sceneComplete': '實景缺口已完成', 'photoDemo.record': '旅程紀錄', 'photoDemo.opening': '正在開啟…', 'photoDemo.reopen': '重新開啟相機', 'photoDemo.open': '開啟相機並開始對位', 'photoDemo.chooseAlbum': '從相簿選取', 'photoDemo.continuous': '系統會持續檢查牌匾與屋簷輪廓', 'photoDemo.score': '目前相似度 {score}%', 'photoDemo.check': '立即檢查對位', 'photoDemo.albumSaving': '相簿照片已選取，正在加入旅程紀錄', 'photoDemo.sceneSaving': '缺口已補齊，照片正在加入旅程紀錄', 'photoDemo.albumUnlocked': '相簿照片已解鎖', 'photoDemo.sceneUnlocked': '實景照片已解鎖', 'photoDemo.next': '下一關', 'photoDemo.privacy': '相機缺口只在裝置上比對，影像不會自動上傳。',
    'photoDemo.insecure': '相機需要 HTTPS 或本機開發環境。', 'photoDemo.denied': '相機權限未開啟，請在瀏覽器網站設定中允許相機後再試一次。', 'photoDemo.noCamera': '找不到可用的相機，請確認裝置相機可正常使用。', 'photoDemo.busy': '相機可能正在被其他應用程式使用，請關閉後再試一次。', 'photoDemo.cameraFailed': '目前無法開啟相機，請確認權限與瀏覽器支援後再試一次。', 'photoDemo.videoFailed': '相機畫面載入失敗', 'photoDemo.alignHelp': '移動手機，讓鏡頭中的牌匾與缺口邊緣重合。', 'photoDemo.comparing': '正在比對缺口中的建築輪廓…', 'photoDemo.notAligned': '尚未對準，目前相似度 {score}%。請繼續移動鏡頭。', 'photoDemo.aligned': '對位成功，正在把鏡頭畫面補進原始照片。', 'photoDemo.compareFailed': '影像比對失敗，請再試一次。', 'photoDemo.albumSelected': '已從相簿選取照片，正在加入旅程紀錄。', 'photoDemo.albumFailed': '照片處理失敗，請重新從相簿選取。', 'photoDemo.referenceFailed': '無法載入萬春宮任務照片', 'photoDemo.saveFailed': '照片儲存失敗，請再試一次。', 'photoDemo.saving': '正在保存照片…',
    'gameScene.kicker': '{temple}小挑戰', 'gameScene.title': '完成小遊戲，解鎖文化故事', 'gameScene.help': '選擇喜歡的玩法，完成任一款即可通過快速體驗。', 'gameScene.badge': '快速體驗', 'gameScene.description': '可自由切換玩法；完成目前選擇的任一遊戲即可通過挑戰。', 'gameScene.complete': '遊戲完成', 'gameScene.completeBody': '你完成了{temple}的連續探索體驗。',
    'minigame.puzzle': '文化拼圖', 'minigame.lantern': '點燈祈福', 'minigame.maze': '文化迷宮', 'minigame.memory': '記憶配對', 'minigame.defaultDescription': '可自由切換玩法；完成目前選擇的任一遊戲即可通過第三關。', 'minigame.choose': '選擇小遊戲', 'minigame.type': '小遊戲類型', 'minigame.loading': '載入小遊戲…',
    'journal.coverAria': '旅行手札封面', 'journal.open': '打開旅行手札', 'journal.coverAlt': '暖色木桌上的青綠色旅行手札', 'journal.coverEyebrow': '文化收藏', 'journal.coverTitle': '我的旅行手札', 'journal.openAria': '打開的旅行手札', 'journal.eyebrow': '我的收藏旅程', 'journal.title': '旅行手札', 'journal.close': '闔上旅行手札', 'journal.emptyTitle': '手札還是空白的', 'journal.emptyBody': '完成第一間宮廟參訪後，旅程會寫進這裡。', 'journal.pagination': '手札翻頁', 'journal.previous': '上一間寺廟', 'journal.next': '下一間寺廟', 'journal.pageStatus': '目前第 {current} 頁，共 {total} 頁', 'journal.photoAlt': '{temple}參訪照片', 'journal.photoCaption': '{date}・參訪留影', 'journal.section': '宮廟小記', 'journal.intro': '寺廟簡介', 'journal.stampAlt': '{temple}紀念印章', 'journal.note': '我的小記錄',
    'entry.title': '登入帳號', 'entry.account': '電子郵件或帳號', 'entry.accountPlaceholder': '請輸入電子郵件或帳號', 'entry.password': '密碼', 'entry.passwordPlaceholder': '請輸入密碼', 'entry.hidePassword': '隱藏密碼', 'entry.showPassword': '顯示密碼', 'entry.signingIn': '登入中…', 'entry.signIn': '登入', 'entry.other': '其他登入方式', 'entry.connecting': '連接 LINE 中…', 'entry.line': '使用 LINE 登入', 'entry.lineFailed': 'LINE 登入失敗，請再試一次', 'entry.signInFailed': '登入失敗，請再試一次', 'entry.connectionFailed': 'LINE 連線失敗，請再試一次', 'entry.testPlayer': '測試玩家',
    'preview.eyebrow': '互動遊戲', 'preview.title': '第三關小遊戲', 'preview.intro': '選擇遊戲開始體驗，完成後仍可切換其他玩法。', 'preview.choose': '選擇遊戲', 'preview.complete': '遊戲完成，可繼續選擇其他玩法。', 'preview.loading': '載入小遊戲測試頁…', 'preview.maze': '文化迷宮', 'preview.memory': '記憶配對', 'preview.puzzle': '拼圖', 'itinerary.loading': '行程載入中', 'session.avatar': '個人頭像',
    'maze.eyebrow': '廟埕尋路', 'maze.title': '文化迷宮', 'maze.instructions': '使用方向鍵或畫面按鈕，帶領小旅人走到終點。', 'maze.board': '文化迷宮盤面', 'maze.traveler': '小旅人', 'maze.goal': '終點', 'maze.complete': '成功抵達終點！共走了 {moves} 步。', 'maze.progress': '目前已走 {moves} 步。', 'maze.controls': '移動控制', 'maze.up': '向上走', 'maze.left': '向左走', 'maze.down': '向下走', 'maze.right': '向右走', 'maze.restart': '再玩一次',
    'itinerary.eyebrow': '下一段文化旅程', 'itinerary.title': '我的行程', 'itinerary.subtitle': '收藏下一次想探索的宮廟', 'itinerary.count': '{count} 個待探索地點',
    'itinerary.emptyTitle': '還沒有安排下一站', 'itinerary.emptyBody': '從地圖找到想探索的宮廟，加入你的行程吧。', 'itinerary.goMap': '前往地圖',
    'itinerary.add': '加入行程', 'itinerary.joined': '已加入行程', 'itinerary.completed': '已完成', 'itinerary.loginToAdd': '登入後加入行程',
    'itinerary.removeConfirm': '要從行程移除嗎？', 'itinerary.cancel': '取消', 'itinerary.remove': '移除', 'itinerary.updateFailed': '無法更新行程',
    'itinerary.viewTemple': '查看宮廟', 'itinerary.back': '返回我的行程', 'itinerary.unavailable': '此宮廟資料目前無法載入', 'itinerary.deity': '主祀：{deity}',
    'friends.eyebrow': '同行旅人', 'friends.title': '好友', 'friends.description': '查看好友的文化探索進度，也可以透過電話或 LINE ID 新增好友。',
    'friends.add': '新增好友', 'friends.addAction': '送出邀請', 'friends.search': '搜尋', 'friends.phone': '電話', 'friends.lineId': 'LINE ID', 'friends.lineFriends': 'LINE 好友', 'friends.lookupType': '好友搜尋方式',
    'friends.summary': '好友進度摘要', 'friends.people': '位好友', 'friends.averageStamps': '平均集章', 'friends.averageCollection': '平均圖鑑', 'friends.stamps': '集章', 'friends.collection': '圖鑑',
    'friends.removeNamed': '刪除好友 {name}', 'friends.added': '已新增 {name}。', 'friends.removed': '已刪除 {name}。', 'friends.notFound': '找不到符合的使用者，請確認資料是否完整。', 'friends.alreadyAdded': '這位使用者已經是你的好友。',
    'friends.demoLookup': '好友搜尋', 'friends.demoNote': '好友邀請狀態會保存在這台裝置。', 'friends.empty': '目前還沒有好友', 'friends.emptyHelp': '新增好友後，就能在這裡比較彼此的文化探索進度。', 'friends.chooseLineFriend': '選擇 LINE 好友', 'friends.chooseLineFriendHelp': '選擇好友並送出遊戲邀請。', 'friends.invite': '邀請', 'friends.invited': '待同意', 'friends.isFriend': '已是好友', 'friends.invitationSent': '已向 {name} 送出好友邀請。', 'friends.invitationCancelled': '已取消對 {name} 的好友邀請。', 'friends.cancelNamedInvitation': '取消對 {name} 的好友邀請', 'friends.pendingApproval': '待同意', 'friends.pendingProgress': '對方同意邀請後，才能查看集章與圖鑑進度。點擊「待同意」可取消邀請。',
    'settings.eyebrow': '遊戲偏好', 'settings.title': '設定', 'settings.description': '調整介面語言與顯示方式，設定會保存在目前裝置。',
    'settings.language': '介面語言', 'settings.languageHelp': '切換共用導覽、任務與介紹文字；有正式英譯的宮廟會一併切換名稱。', 'settings.chinese': '繁體中文', 'settings.english': 'English',
    'settings.motion': '減少動畫', 'settings.motionHelp': '縮短地圖移動、蓋章與選單動畫，適合容易暈動或希望快速操作的玩家。',
    'settings.contrast': '高對比文字', 'settings.contrastHelp': '加深文字與邊框，提升戶外環境下的可讀性。',
    'settings.storage': '資料與隱私', 'settings.storageHelp': '遊戲進度、照片、個人資料及偏好目前只保存在這台裝置；照片不會自動上傳。', 'settings.saved': '設定已自動儲存。',
    'map.selectCounty': '全台地圖：選擇縣市', 'map.countyLabel': '選擇縣市', 'map.districtLabel': '選擇鄉鎮市區', 'map.selectDistrict': '{county}：全部鄉鎮市區', 'map.overview': '全台地圖', 'map.search': '搜尋{region}宮廟', 'map.searchLabel': '搜尋宮廟', 'map.results': '宮廟搜尋結果', 'map.noResults': '沒有符合的宮廟', 'map.loading': '宮廟資料載入中…', 'map.loadFailed': '載入失敗', 'map.noTemples': '這個區域目前沒有符合條件的宮廟', 'map.notFound': '找不到這間宮廟',
    'profile.eyebrow': '玩家帳戶', 'profile.title': '個人資料', 'profile.description': '自訂資料只會保存在目前裝置，LINE 帳號連結維持不變。', 'profile.avatar': '大頭照', 'profile.currentAvatar': '目前的大頭照', 'profile.replaceAvatar': '替換大頭照', 'profile.restoreAvatar': '恢復 LINE 頭像', 'profile.avatarHelp': '圖片會裁切成正方形並縮小後保存。', 'profile.name': '姓名', 'profile.lineId': 'LINE 使用者 ID', 'profile.lineIdHelp': '由 LINE LIFF 提供，系統無法取得或修改使用者公開設定的 LINE ID。', 'profile.phone': '電話', 'profile.phonePlaceholder': '例如：0912-345-678', 'profile.save': '儲存個人資料', 'profile.saving': '儲存中…', 'profile.saved': '個人資料已儲存在這台裝置。', 'profile.logout': '登出', 'profile.readFailed': '無法讀取頭像圖片', 'profile.chooseImage': '請選擇圖片檔案', 'profile.tooLarge': '頭像原圖不可超過 8 MB', 'profile.invalidSize': '頭像圖片尺寸不正確', 'profile.processFailed': '無法處理頭像', 'profile.saveFailed': '個人資料保存失敗',
    'task.stamp': '數位蓋章', 'task.photo': '找點拍照', 'task.puzzle': '文化小遊戲', 'task.label': '任務 {order}', 'task.progress': '任務進度', 'task.completedAt': '完成時間：{time}', 'task.locked': '鎖定', 'task.available': '可開始', 'task.completed': '已完成', 'task.start': '開始', 'task.review': '回顧', 'task.finishPrevious': '請先完成任務 {order}',
    'temple.name': '萬春宮', 'temple.back': '返回萬春宮', 'temple.location': '台中市中區', 'temple.routeProgress': '探索進度：{completed} / {total} 項任務完成', 'temple.completeTitle': '萬春宮探索任務已完成', 'temple.completeBody': '三項任務都已完成，萬春宮錨點已在地圖上點亮。', 'temple.viewStamps': '查看集章簿', 'temple.viewCollection': '查看圖鑑', 'temple.startExplore': '開始探索任務', 'temple.photoAlt': '萬春宮探索照片', 'temple.next': '請依序完成三項任務，下一步：{task}', 'temple.list': '任務清單', 'temple.hint.stamp': '依畫面說明完成模擬感應；完成三項任務後，紀念章會加入集章簿。', 'temple.hint.photo': '到指定位置拍攝或選圖，對位後補上缺口並保存。', 'temple.hint.puzzle': '完成拼圖後即可閱讀文化故事。',
    'mission.alreadyDone': '任務已完成', 'mission.previousFirst': '請先完成前一項任務', 'mission.back': '返回萬春宮', 'mission.saving': '正在保存…', 'mission.saveFailed': '保存失敗，請重試',
    'stamp.demo': 'LINE Touch 感應', 'stamp.step1': '到萬春宮服務台找到活動印章。', 'stamp.step2': '將手機靠近印章感應區，按下「模擬感應」。', 'stamp.step3': '感應完成後會蓋下數位印章；完成三項任務後收錄紀念章。', 'stamp.intro': '尚未感應', 'stamp.sensing': '模擬感應中…', 'stamp.stamping': '感應完成，蓋章中…', 'stamp.done': '數位蓋章已完成。', 'stamp.start': '模擬感應', 'stamp.sensingButton': '感應中…', 'stamp.finishedButton': '已完成感應', 'stamp.retry': '重新感應',
    'photo.eyebrow': '宮廟找點', 'photo.title': '拍照補上文化場景', 'photo.description': '可拍照或從裝置選取圖片，確認後會保存在這台裝置。', 'photo.choose': '拍照或選擇照片', 'photo.rechoose': '重新選擇照片', 'photo.previewAlt': '準備保存的萬春宮任務照片', 'photo.confirm': '請確認照片後完成任務', 'photo.empty': '尚未選擇照片', 'photo.saving': '儲存中…', 'photo.save': '保存照片並完成任務',
    'puzzle.eyebrow': '廟宇尋寶', 'puzzle.title': '3 × 3 拼圖', 'puzzle.instructions': '點選兩塊碎片交換位置，將圖片恢復完整。每次開始都會重新打亂。', 'puzzle.board': '3 × 3 拼圖棋盤', 'puzzle.tile': '第 {position} 格，目前是圖片第 {tile} 塊{selected}', 'puzzle.selected': '，已選取', 'puzzle.complete': '完成！你已成功拼回萬春宮。', 'puzzle.selectFirst': '請先選擇一塊碎片。', 'puzzle.selectSecond': '再選擇另一塊碎片即可交換。', 'puzzle.restart': '再玩一次',
    'temple.preview': '宮廟簡介', 'temple.closePreview': '關閉宮廟簡介', 'temple.details': '查看詳情', 'temple.explore': '探索任務', 'temple.imagePending': '宮廟圖片待補', 'temple.loading': '宮廟資料載入中…', 'temple.notFound': '找不到這間宮廟', 'temple.religion': '宗教分類', 'temple.deity': '主祀神祇', 'temple.address': '地址', 'temple.phone': '電話', 'temple.history': '歷史', 'temple.features': '特色', 'temple.additionalSources': '補充內容來源：{sources}', 'temple.imageSource': '圖片來源：{source}', 'temple.dataSource': '資料來源：', 'temple.publicData': '公開宗教場所資料', 'temple.notInDemo': '尚無任務紀錄', 'temple.noRecord': '尚無任務紀錄', 'temple.record': '已完成 {completed}／{total} 項任務，最近一次：{time}',
    'story.back': '返回任務頁', 'story.next': '下一關', 'story.kicker': '萬春宮 · 任務完成', 'story.title': '{task}的小故事', 'story.fallback': '完成「{task}」後，你在萬春宮留下了一段探索記錄。沿著任務一步步前進，這趟文化小旅行也多了一個值得回看的片段。', 'story.imageAlt': '萬春宮探索紀錄', 'story.imagePending': '圖片待補：需使用具來源／授權的素材。', 'story.source': '來源：', 'story.demoSource': '萬春宮活動流程紀錄', 'story.backMap': '返回地圖',
  },
  en: {
    'nav.taiwan': 'Taiwan', 'nav.stamps': 'Stamps', 'nav.collection': 'Gallery', 'nav.journal': 'Journal', 'nav.points': 'Points', 'nav.itinerary': 'My Trip',
    'nav.collapse': 'Collapse bottom navigation', 'nav.expand': 'Expand bottom navigation', 'nav.main': 'Main navigation',
    'drawer.open': 'Open menu', 'drawer.close': 'Close menu', 'drawer.navigation': 'Navigation menu', 'drawer.other': 'Other pages',
    'drawer.stampbook': 'Stamp Book', 'drawer.photos': 'Photo Gallery', 'drawer.news': 'Events', 'drawer.settings': 'Settings', 'drawer.friends': 'Friends', 'drawer.profile': 'Profile', 'drawer.credits': 'Data & Licenses',
    'session.current': 'Current player', 'session.disconnected': 'LINE not connected', 'session.progress': 'Wanchun Temple missions {completed}/{total}', 'session.loginHint': 'Sign in before starting missions', 'session.mock': 'Signed in', 'session.connect': 'Connect LINE',
    'common.backMap': 'Back to map', 'common.retry': 'Retry', 'common.close': 'Close', 'common.loading': 'Loading…', 'common.error': 'Something went wrong', 'common.noData': 'No data yet',
    'collection.eyebrow': 'Cultural Memories', 'collection.title': 'Photo Gallery', 'collection.collected': '{count}/{total} districts collected', 'collection.intro': 'Complete every temple in a district to add its cultural memory photo to your gallery.',
    'collection.unlockCentral': 'Complete every temple in Central District to unlock', 'collection.explore': 'Start exploring', 'collection.aria': 'Cultural memories grouped by administrative region', 'collection.empty': 'Not collected', 'collection.loading': 'Loading administrative regions…', 'collection.loadFailed': 'Unable to load administrative regions', 'collection.regionCount': '{count} districts', 'collection.districtCount': '{count} districts',
    'collection.centralLocation': 'Central District, Taichung City', 'collection.centralTitle': 'Historic Central District Market', 'collection.centralDescription': 'Crowded streets and vendors preserve a glimpse of Central District’s commercial heyday.', 'collection.centralImageAlt': 'Historic overhead view of a busy market street in Central District, Taichung', 'collection.centralSource': 'Historical photo supplied by the user; original archive and licensing details are pending.',
    'stampbook.loading': 'Organizing temple stamps…', 'stampbook.loadFailed': 'Unable to load Stamp Book data', 'stampbook.reload': 'Reload', 'stampbook.eyebrow': 'Temple Culture Collection', 'stampbook.title': 'Stamp Book', 'stampbook.collectedCount': '{count}/{total} temples collected',
    'stampbook.emptyTitle': 'Your Stamp Book is empty', 'stampbook.emptyBody': 'Complete your first temple exploration to collect its stamp.', 'stampbook.goMap': 'Go to map', 'stampbook.aria': 'Temple stamps grouped by city, county, and district', 'stampbook.noMatches': 'No matching stamps', 'stampbook.adjust': 'Change the collection filter and try again.',
    'stampbook.completedDistricts': '{completed}/{total} districts complete', 'stampbook.templeCount': '{count} temples', 'stampbook.none': 'Not collected', 'stampbook.collected': 'Collected', 'stampbook.notCollected': 'Not collected', 'stampbook.cardLabel': '{temple}, {location}, {state}',
    'stampbook.closeDetail': 'Close stamp details', 'stampbook.exclusive': 'Temple Stamp', 'stampbook.stampAlt': '{temple} stamp', 'stampbook.unknown': 'Stamp not collected', 'stampbook.acquiredDate': 'Collected: {date}', 'stampbook.acquiredDescription': 'Collected after completing the {temple} exploration.', 'stampbook.lockedDescription': 'Complete this temple’s exploration to collect its stamp.', 'stampbook.viewTemple': 'View temple', 'stampbook.viewJournal': 'View journey record',
    'collectible.close': 'Close collectible details', 'collectible.date': 'Collected · {date}',
    'news.eyebrow': 'Cultural Event Updates', 'news.title': 'Events', 'news.intro': 'Follow festival routes and pilgrimage trails to collect limited cultural memories.', 'news.tags': 'Event tags', 'news.limited': '#LimitedTime', 'news.taichung': '#Taichung', 'news.mazu': '#Mazu', 'news.eventTitle': 'Dajia Mazu Pilgrimage', 'news.time': 'Dates', 'news.region': 'Regions', 'news.regions': 'Taichung · Changhua · Yunlin · Chiayi',
    'news.memory': 'Event Gallery', 'news.unlocked': 'Unlocked', 'news.locked': 'Locked', 'news.memoryLocked': 'Event gallery item is locked', 'news.memoryZoom': 'Enlarge the Dajia Mazu Pilgrimage historical photo', 'news.imageAlt': 'Historical photo of the Dajia Mazu Pilgrimage', 'news.stamps': 'Limited Stamps', 'news.stampsHelp': 'Unlock them in order by completing route missions', 'news.stampRow': '{count} limited stamps: {state}', 'news.stampZoom': 'Enlarge {stamp} stamp', 'news.stampAlt': '{stamp} stamp', 'news.eventLocation': 'Dajia Mazu Pilgrimage · Limited Event', 'news.stampTitle': '{stamp} Commemorative Stamp', 'news.stampDescription': 'Collected after completing route stage {number}.', 'news.memoryTitle': 'Dajia Mazu Pilgrimage Cultural Memory', 'news.memoryDescription': 'A historical memory collected by completing the limited pilgrimage event.',
    'news.stamp.0': 'Departure', 'news.stamp.1': 'Changhua', 'news.stamp.2': 'Xiluo', 'news.stamp.3': 'Xingang', 'news.stamp.4': 'Birthday Rite', 'news.stamp.5': 'Return', 'news.stamp.6': 'Enshrinement',
    'reward.remaining': '{count} more rewards after confirmation', 'reward.confirm': 'Confirm',
    'demo.eyebrow': 'Presentation Tools', 'demo.title': 'Demo Control Panel', 'demo.close': 'Close', 'demo.intro': 'These switches remain active on this device after signing out or changing LINE accounts.', 'demo.loginReset': 'Sign in before resetting the current account.', 'demo.resetDone': 'Current account progress was reset',
    'demo.central.title': 'Complete Central District', 'demo.central.description': 'Complete every temple in Central District, light all markers, and unlock all stamps and its gallery item.', 'demo.map.title': 'Color Taiwan', 'demo.map.description': 'Apply fixed completed and in-progress colors across Taiwan.', 'demo.event.title': 'Limited Event', 'demo.event.description': 'Complete all seven Dajia Mazu Pilgrimage stamps and unlock its gallery item.', 'demo.rewards.title': 'Reward Pop-ups', 'demo.rewards.description': 'Show the stamp, gallery, LINE POINTS, and permanent sticker rewards in order.', 'demo.reset.title': 'Reset Current Account', 'demo.reset.description': 'Clear missions, stamps, gallery items, itinerary, profile picture, and local preferences.',
    'experience.temple': 'Wanchun Temple', 'experience.location': 'Central District, Taichung City', 'experience.back': 'Back to Wanchun Temple', 'experience.title': '{temple} Missions', 'experience.reset': 'Restart', 'experience.resetTitle': 'Restart the experience', 'experience.progress': 'Exploration progress', 'experience.touch': 'LINE Touch', 'experience.photo': 'Photo Hunt', 'experience.game': 'Interactive Game', 'experience.disclaimer': 'LINE Touch is simulated. Photos can be aligned with the device camera or selected from your album. Images are never uploaded automatically.',
    'touch.kicker': 'LINE Touch · Cultural Exploration', 'touch.success': 'Touch successful', 'touch.detecting': 'Detecting…', 'touch.title': 'Start temple exploration', 'touch.opened': '{temple} exploration is open', 'touch.keepNear': 'Keep your phone near the touch area', 'touch.help': 'Hold your phone near the touch area to begin today’s cultural missions.', 'touch.simulate': 'Simulate Touch', 'touch.reading': 'Reading temple exploration details', 'touch.stamping': 'Your exploration stamp is about to be applied',
    'stampScene.defaultContinue': 'Start Photo Hunt', 'stampScene.certificate': 'Exploration Pass', 'stampScene.acquiring': 'Collecting Stamp', 'stampScene.opened': '{temple} exploration is open', 'stampScene.title': 'Applying Temple Stamp', 'stampScene.saved': 'Your stamp has been added to the exploration card.', 'stampScene.wait': 'Touch successful. Please wait.', 'stampScene.journey': 'Cultural Journey', 'stampScene.slot': 'Stamp Area', 'stampScene.alt': '{temple} red stamp', 'stampScene.impact': 'Stamp!', 'stampScene.complete': '{temple} digital stamp complete',
    'transition.photoTitle': 'Prepare for Photo Hunt', 'transition.gameTitle': 'Loading game…', 'transition.photoBody': 'Record your exploration at {temple}', 'transition.gameBody': 'Get ready for the {temple} challenge',
    'photoDemo.kicker': 'Photo Hunt · Scene Alignment', 'photoDemo.completeTitle': 'Photo Hunt Complete', 'photoDemo.unlockedTitle': 'Full Photo Unlocked', 'photoDemo.title': 'Fill the Photo Gap', 'photoDemo.nextGame': 'Next, complete a {temple} game!', 'photoDemo.help': 'Align the live camera with the missing area of the reference photo to unlock it.', 'photoDemo.stageLabel': '{temple} reference photo with a live camera view in the center gap', 'photoDemo.camera': 'Camera view', 'photoDemo.checking': 'Checking position…', 'photoDemo.resultAlt': 'Completed scene-alignment photo at {temple}', 'photoDemo.album': 'Album photo', 'photoDemo.sceneComplete': 'Live scene completed', 'photoDemo.record': 'Journey Record', 'photoDemo.opening': 'Opening…', 'photoDemo.reopen': 'Open camera again', 'photoDemo.open': 'Open camera and align', 'photoDemo.chooseAlbum': 'Choose from album', 'photoDemo.continuous': 'The system checks the plaque and roofline outlines', 'photoDemo.score': 'Current similarity: {score}%', 'photoDemo.check': 'Check alignment now', 'photoDemo.albumSaving': 'Album photo selected and being added to your journey record', 'photoDemo.sceneSaving': 'Gap completed and photo being added to your journey record', 'photoDemo.albumUnlocked': 'Album photo unlocked', 'photoDemo.sceneUnlocked': 'Live photo unlocked', 'photoDemo.next': 'Next Mission', 'photoDemo.privacy': 'Camera matching happens only on this device. Images are not uploaded automatically.',
    'photoDemo.insecure': 'The camera requires HTTPS or a local development environment.', 'photoDemo.denied': 'Camera permission is disabled. Allow camera access in your browser settings and try again.', 'photoDemo.noCamera': 'No available camera was found. Check that your device camera is working.', 'photoDemo.busy': 'Another app may be using the camera. Close it and try again.', 'photoDemo.cameraFailed': 'Unable to open the camera. Check browser support and permissions.', 'photoDemo.videoFailed': 'Unable to load the camera view', 'photoDemo.alignHelp': 'Move your phone until the plaque and roofline align with the edge of the gap.', 'photoDemo.comparing': 'Comparing the architecture inside the gap…', 'photoDemo.notAligned': 'Not aligned yet. Current similarity: {score}%. Keep moving the camera.', 'photoDemo.aligned': 'Alignment successful. Filling the reference photo with the live camera view.', 'photoDemo.compareFailed': 'Image comparison failed. Please try again.', 'photoDemo.albumSelected': 'Album photo selected and being added to your journey record.', 'photoDemo.albumFailed': 'Unable to process the photo. Choose another photo from your album.', 'photoDemo.referenceFailed': 'Unable to load the Wanchun Temple mission photo', 'photoDemo.saveFailed': 'Unable to save the photo. Please try again.', 'photoDemo.saving': 'Saving photo…',
    'gameScene.kicker': '{temple} Challenge', 'gameScene.title': 'Complete a game to unlock the cultural story', 'gameScene.help': 'Choose a game and complete any one to finish the quick experience.', 'gameScene.badge': 'Quick Experience', 'gameScene.description': 'Switch freely between games. Complete any selected game to pass.', 'gameScene.complete': 'Game Complete', 'gameScene.completeBody': 'You completed the continuous {temple} exploration experience.',
    'minigame.puzzle': 'Culture Puzzle', 'minigame.lantern': 'Prayer Lanterns', 'minigame.maze': 'Culture Maze', 'minigame.memory': 'Memory Match', 'minigame.defaultDescription': 'Switch freely between games. Complete any selected game to pass mission three.', 'minigame.choose': 'Choose a Game', 'minigame.type': 'Game type', 'minigame.loading': 'Loading game…',
    'journal.coverAria': 'Travel journal cover', 'journal.open': 'Open travel journal', 'journal.coverAlt': 'Teal travel journal on a warm wooden desk', 'journal.coverEyebrow': 'Cultural Collection', 'journal.coverTitle': 'My Travel Journal', 'journal.openAria': 'Open travel journal', 'journal.eyebrow': 'My Collection Journey', 'journal.title': 'Travel Journal', 'journal.close': 'Close travel journal', 'journal.emptyTitle': 'Your journal is still blank', 'journal.emptyBody': 'Complete your first temple visit to add a page to the journey.', 'journal.pagination': 'Journal pages', 'journal.previous': 'Previous temple', 'journal.next': 'Next temple', 'journal.pageStatus': 'Page {current} of {total}', 'journal.photoAlt': '{temple} visit photo', 'journal.photoCaption': '{date} · Visit Photo', 'journal.section': 'Temple Notes', 'journal.intro': 'Temple Introduction', 'journal.stampAlt': '{temple} commemorative stamp', 'journal.note': 'My Notes',
    'entry.title': 'Sign In', 'entry.account': 'Email or account', 'entry.accountPlaceholder': 'Enter your email or account', 'entry.password': 'Password', 'entry.passwordPlaceholder': 'Enter your password', 'entry.hidePassword': 'Hide password', 'entry.showPassword': 'Show password', 'entry.signingIn': 'Signing in…', 'entry.signIn': 'Sign in', 'entry.other': 'Other sign-in methods', 'entry.connecting': 'Connecting to LINE…', 'entry.line': 'Sign in with LINE', 'entry.lineFailed': 'LINE sign-in failed. Please try again.', 'entry.signInFailed': 'Sign-in failed. Please try again.', 'entry.connectionFailed': 'Unable to connect to LINE. Please try again.', 'entry.testPlayer': 'Test Player',
    'preview.eyebrow': 'Interactive Games', 'preview.title': 'Mission Three Games', 'preview.intro': 'Choose a game to begin. You can switch to another game after completing one.', 'preview.choose': 'Choose a game', 'preview.complete': 'Game complete. You can continue trying other games.', 'preview.loading': 'Loading game preview…', 'preview.maze': 'Culture Maze', 'preview.memory': 'Memory Match', 'preview.puzzle': 'Puzzle', 'itinerary.loading': 'Loading itinerary', 'session.avatar': 'Profile picture',
    'maze.eyebrow': 'Temple Courtyard Trail', 'maze.title': 'Culture Maze', 'maze.instructions': 'Use the arrow keys or on-screen controls to guide the traveler to the goal.', 'maze.board': 'Culture maze board', 'maze.traveler': 'Traveler', 'maze.goal': 'Goal', 'maze.complete': 'Goal reached in {moves} moves!', 'maze.progress': '{moves} moves so far.', 'maze.controls': 'Movement controls', 'maze.up': 'Move up', 'maze.left': 'Move left', 'maze.down': 'Move down', 'maze.right': 'Move right', 'maze.restart': 'Play again',
    'itinerary.eyebrow': 'Your next cultural journey', 'itinerary.title': 'My Trip', 'itinerary.subtitle': 'Save temples to explore next', 'itinerary.count': '{count} places to explore',
    'itinerary.emptyTitle': 'No next stop yet', 'itinerary.emptyBody': 'Find a temple on the map and add it to your trip.', 'itinerary.goMap': 'Go to map',
    'itinerary.add': 'Add to trip', 'itinerary.joined': 'Added to trip', 'itinerary.completed': 'Completed', 'itinerary.loginToAdd': 'Sign in to add',
    'itinerary.removeConfirm': 'Remove this temple from your trip?', 'itinerary.cancel': 'Cancel', 'itinerary.remove': 'Remove', 'itinerary.updateFailed': 'Unable to update trip',
    'itinerary.viewTemple': 'View temple', 'itinerary.back': 'Back to My Trip', 'itinerary.unavailable': 'Temple data is currently unavailable', 'itinerary.deity': 'Primary deity: {deity}',
    'friends.eyebrow': 'Fellow travelers', 'friends.title': 'Friends', 'friends.description': 'See your friends’ cultural exploration progress, or add someone by phone number or LINE ID.',
    'friends.add': 'Add friend', 'friends.addAction': 'Send invite', 'friends.search': 'Search', 'friends.phone': 'Phone', 'friends.lineId': 'LINE ID', 'friends.lineFriends': 'LINE friends', 'friends.lookupType': 'Friend search method',
    'friends.summary': 'Friend progress summary', 'friends.people': 'friends', 'friends.averageStamps': 'Avg. stamps', 'friends.averageCollection': 'Avg. gallery', 'friends.stamps': 'Stamps', 'friends.collection': 'Gallery',
    'friends.removeNamed': 'Remove {name}', 'friends.added': '{name} was added.', 'friends.removed': '{name} was removed.', 'friends.notFound': 'No matching user was found. Check the full value and try again.', 'friends.alreadyAdded': 'This person is already your friend.',
    'friends.demoLookup': 'Friend search', 'friends.demoNote': 'Friend invitation status is saved on this device.', 'friends.empty': 'No friends yet', 'friends.emptyHelp': 'Add a friend to compare your cultural exploration progress.', 'friends.chooseLineFriend': 'Choose a LINE friend', 'friends.chooseLineFriendHelp': 'Choose a friend and send a game invitation.', 'friends.invite': 'Invite', 'friends.invited': 'Pending', 'friends.isFriend': 'Friends', 'friends.invitationSent': 'Invitation sent to {name}.', 'friends.invitationCancelled': 'Invitation to {name} was cancelled.', 'friends.cancelNamedInvitation': 'Cancel invitation to {name}', 'friends.pendingApproval': 'Pending', 'friends.pendingProgress': 'Stamp and gallery progress will appear after this invitation is accepted. Select “Pending” to cancel.',
    'settings.eyebrow': 'Game preferences', 'settings.title': 'Settings', 'settings.description': 'Choose the interface language and display preferences. Settings are saved on this device.',
    'settings.language': 'Interface language', 'settings.languageHelp': 'Changes navigation, missions, and introductions. Temples with registered English names are translated as well.', 'settings.chinese': '繁體中文', 'settings.english': 'English',
    'settings.motion': 'Reduce motion', 'settings.motionHelp': 'Shortens map, stamp, and menu animations for faster and more comfortable use.',
    'settings.contrast': 'High-contrast text', 'settings.contrastHelp': 'Darkens text and borders for better readability outdoors.',
    'settings.storage': 'Data and privacy', 'settings.storageHelp': 'Progress, photos, profile details, and preferences are currently stored only on this device. Photos are not uploaded automatically.', 'settings.saved': 'Settings saved automatically.',
    'map.selectCounty': 'Taiwan map: select a city or county', 'map.countyLabel': 'Select city or county', 'map.districtLabel': 'Select district', 'map.selectDistrict': '{county}: all districts', 'map.overview': 'Taiwan map', 'map.search': 'Search temples in {region}', 'map.searchLabel': 'Search temples', 'map.results': 'Temple search results', 'map.noResults': 'No matching temples', 'map.loading': 'Loading temple data…', 'map.loadFailed': 'Unable to load', 'map.noTemples': 'No matching temples in this area', 'map.notFound': 'Temple not found',
    'profile.eyebrow': 'Player account', 'profile.title': 'Profile', 'profile.description': 'Custom details are stored on this device. Your linked LINE account remains unchanged.', 'profile.avatar': 'Profile picture', 'profile.currentAvatar': 'Current profile picture', 'profile.replaceAvatar': 'Change picture', 'profile.restoreAvatar': 'Restore LINE picture', 'profile.avatarHelp': 'The image is cropped to a square and resized before saving.', 'profile.name': 'Name', 'profile.lineId': 'LINE user ID', 'profile.lineIdHelp': 'Provided by LINE LIFF. The public LINE ID is not available and cannot be changed here.', 'profile.phone': 'Phone', 'profile.phonePlaceholder': 'Example: 0912-345-678', 'profile.save': 'Save profile', 'profile.saving': 'Saving…', 'profile.saved': 'Profile saved on this device.', 'profile.logout': 'Log out', 'profile.readFailed': 'Unable to read the profile image', 'profile.chooseImage': 'Choose an image file', 'profile.tooLarge': 'The original image must be 8 MB or smaller', 'profile.invalidSize': 'The profile image dimensions are invalid', 'profile.processFailed': 'Unable to process the profile image', 'profile.saveFailed': 'Unable to save profile details',
    'task.stamp': 'Digital Stamp', 'task.photo': 'Photo Hunt', 'task.puzzle': 'Culture Minigames', 'task.label': 'Mission {order}', 'task.progress': 'Mission progress', 'task.completedAt': 'Completed: {time}', 'task.locked': 'Locked', 'task.available': 'Available', 'task.completed': 'Completed', 'task.start': 'Start', 'task.review': 'Review', 'task.finishPrevious': 'Complete mission {order} first',
    'temple.name': 'Wanchun Temple', 'temple.back': 'Back to Wanchun Temple', 'temple.location': 'Central District, Taichung', 'temple.routeProgress': 'Exploration progress: {completed}/{total} missions completed', 'temple.completeTitle': 'Wanchun Temple exploration complete', 'temple.completeBody': 'All three missions are complete. The Wanchun Temple marker is now lit.', 'temple.viewStamps': 'View Stamp Book', 'temple.viewCollection': 'View Gallery', 'temple.startExplore': 'Start Exploration', 'temple.photoAlt': 'Wanchun Temple exploration photo', 'temple.next': 'Complete the missions in order. Next: {task}', 'temple.list': 'Mission list', 'temple.hint.stamp': 'Complete the LINE Touch step. The memorial stamp is added after all three missions.', 'temple.hint.photo': 'Take or select a photo, align the scene, and save it.', 'temple.hint.puzzle': 'Complete the puzzle to unlock a cultural story.',
    'mission.alreadyDone': 'Mission completed', 'mission.previousFirst': 'Complete the previous mission first', 'mission.back': 'Back to Wanchun Temple', 'mission.saving': 'Saving…', 'mission.saveFailed': 'Unable to save. Please try again.',
    'stamp.demo': 'LINE Touch', 'stamp.step1': 'Find the event stamp at the Wanchun Temple service desk.', 'stamp.step2': 'Hold your phone near the stamp area and tap “Simulate Touch.”', 'stamp.step3': 'The digital stamp is applied now; the memorial stamp is collected after all three missions.', 'stamp.intro': 'Waiting for touch', 'stamp.sensing': 'Simulating LINE Touch…', 'stamp.stamping': 'Touch detected. Applying stamp…', 'stamp.done': 'Digital stamp complete.', 'stamp.start': 'Simulate Touch', 'stamp.sensingButton': 'Detecting…', 'stamp.finishedButton': 'Touch completed', 'stamp.retry': 'Try again',
    'photo.eyebrow': 'Temple Photo Hunt', 'photo.title': 'Complete the cultural scene', 'photo.description': 'Take or select a photo and save it on this device.', 'photo.choose': 'Take or choose a photo', 'photo.rechoose': 'Choose another photo', 'photo.previewAlt': 'Selected Wanchun Temple mission photo', 'photo.confirm': 'Confirm the photo to complete this mission', 'photo.empty': 'No photo selected', 'photo.saving': 'Saving…', 'photo.save': 'Save photo and complete mission',
    'puzzle.eyebrow': 'Temple Treasure Hunt', 'puzzle.title': '3 × 3 Puzzle', 'puzzle.instructions': 'Select two tiles to swap them and restore the image. The board is reshuffled every time.', 'puzzle.board': '3 × 3 puzzle board', 'puzzle.tile': 'Position {position}, currently image tile {tile}{selected}', 'puzzle.selected': ', selected', 'puzzle.complete': 'Complete! You restored the Wanchun Temple image.', 'puzzle.selectFirst': 'Select a tile first.', 'puzzle.selectSecond': 'Select another tile to swap them.', 'puzzle.restart': 'Play again',
    'temple.preview': 'Temple introduction', 'temple.closePreview': 'Close temple introduction', 'temple.details': 'View details', 'temple.explore': 'Explore missions', 'temple.imagePending': 'Temple image pending', 'temple.loading': 'Loading temple data…', 'temple.notFound': 'Temple not found', 'temple.religion': 'Religion', 'temple.deity': 'Primary deity', 'temple.address': 'Address', 'temple.phone': 'Phone', 'temple.history': 'History', 'temple.features': 'Features', 'temple.additionalSources': 'Additional sources: {sources}', 'temple.imageSource': 'Image source: {source}', 'temple.dataSource': 'Data source: ', 'temple.publicData': 'Public religious-place dataset', 'temple.notInDemo': 'No mission records yet', 'temple.noRecord': 'No mission records yet', 'temple.record': '{completed}/{total} missions completed. Latest: {time}',
    'story.back': 'Back to missions', 'story.next': 'Next mission', 'story.kicker': 'Wanchun Temple · Mission complete', 'story.title': 'The story of {task}', 'story.fallback': 'After completing “{task},” you left a new exploration record at Wanchun Temple. Each mission adds another memory to this cultural journey.', 'story.imageAlt': 'Wanchun Temple exploration record', 'story.imagePending': 'Image pending: licensed or properly sourced material is required.', 'story.source': 'Source: ', 'story.demoSource': 'Wanchun Temple activity record', 'story.backMap': 'Back to map',
  },
}

function loadSettings() {
  try {
    const stored = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}')
    return { ...DEFAULT_SETTINGS, ...stored }
  } catch {
    return DEFAULT_SETTINGS
  }
}

export function SettingsProvider({ children }) {
  const [settings, setSettings] = useState(loadSettings)

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(settings))
    document.documentElement.lang = settings.language
    document.documentElement.dataset.reduceMotion = String(settings.reduceMotion)
    document.documentElement.dataset.highContrast = String(settings.highContrast)
  }, [settings])

  const value = useMemo(() => {
    const messages = MESSAGES[settings.language] ?? MESSAGES['zh-TW']
    return {
      ...settings,
      setSetting(key, settingValue) { setSettings(current => ({ ...current, [key]: settingValue })) },
      t(key, values) { return formatMessage(messages[key] ?? MESSAGES['zh-TW'][key] ?? key, values) },
    }
  }, [settings])

  return <SettingsContext.Provider value={value}>{children}</SettingsContext.Provider>
}

